SRCS=DDMethod

proceedingsversion:
	pdflatex ${SRCS}.tex
#	bibtex $(SRCS)
#	pdflatex ${SRCS}.tex
#	pdflatex ${SRCS}.tex

nonreferences:
#	pdflatex ${SRCS}.tex
#	pdflatex ${SRCS}.tex

clean:
	rm -rf $(SRCS).ps $(SRCS).dvi $(SRCS).log
	rm -rf $(SRCS).toc $(SRCS).blg $(SRCS).bbl
	rm -rf $(SRCS).aux $(SRCS).out $(SRCS).pdf
	rm -rf *~ *.aux *.log *.xml *.bcf *.bbl *.blg *.out *.pdf *.gz *.lof *.lot *.loa *.aux

